INSERT INTO dbo.circuits (
        [circuitId],
        [circuitRef],
        [name],
        [location],
        [country],
        [lat],
        [lng],
        [alt],
        [url]
    )
VALUES (
        1,
        N'albert_park',
        N'Albert Park Grand Prix Circuit',
        N'Melbourne',
        N'Australia',
        -37.8497,
        144.968,
        10,
        N'http://en.wikipedia.org/wiki/Melbourne_Grand_Prix_Circuit'
    ),
    (
        2,
        N'sepang',
        N'Sepang International Circuit',
        N'Kuala Lumpur',
        N'Malaysia',
        2.76083,
        101.738,
        18,
        N'http://en.wikipedia.org/wiki/Sepang_International_Circuit'
    ),
    (
        3,
        N'bahrain',
        N'Bahrain International Circuit',
        N'Sakhir',
        N'Bahrain',
        26.0325,
        50.5106,
        7,
        N'http://en.wikipedia.org/wiki/Bahrain_International_Circuit'
    ),
    (
        4,
        N'catalunya',
        N'Circuit de Barcelona-Catalunya',
        N'Montmeló',
        N'Spain',
        41.57,
        2.26111,
        109,
        N'http://en.wikipedia.org/wiki/Circuit_de_Barcelona-Catalunya'
    ),
    (
        5,
        N'istanbul',
        N'Istanbul Park',
        N'Istanbul',
        N'Turkey',
        40.9517,
        29.405,
        130,
        N'http://en.wikipedia.org/wiki/Istanbul_Park'
    ),
    (
        6,
        N'monaco',
        N'Circuit de Monaco',
        N'Monte-Carlo',
        N'Monaco',
        43.7347,
        7.42056,
        7,
        N'http://en.wikipedia.org/wiki/Circuit_de_Monaco'
    ),
    (
        7,
        N'villeneuve',
        N'Circuit Gilles Villeneuve',
        N'Montreal',
        N'Canada',
        45.5,
        -73.5228,
        13,
        N'http://en.wikipedia.org/wiki/Circuit_Gilles_Villeneuve'
    ),
    (
        8,
        N'magny_cours',
        N'Circuit de Nevers Magny-Cours',
        N'Magny Cours',
        N'France',
        46.8642,
        3.16361,
        228,
        N'http://en.wikipedia.org/wiki/Circuit_de_Nevers_Magny-Cours'
    ),
    (
        9,
        N'silverstone',
        N'Silverstone Circuit',
        N'Silverstone',
        N'UK',
        52.0786,
        -1.01694,
        153,
        N'http://en.wikipedia.org/wiki/Silverstone_Circuit'
    ),
    (
        10,
        N'hockenheimring',
        N'Hockenheimring',
        N'Hockenheim',
        N'Germany',
        49.3278,
        8.56583,
        103,
        N'http://en.wikipedia.org/wiki/Hockenheimring'
    ),
    (
        11,
        N'hungaroring',
        N'Hungaroring',
        N'Budapest',
        N'Hungary',
        47.5789,
        19.2486,
        264,
        N'http://en.wikipedia.org/wiki/Hungaroring'
    ),
    (
        12,
        N'valencia',
        N'Valencia Street Circuit',
        N'Valencia',
        N'Spain',
        39.4589,
        -0.331667,
        4,
        N'http://en.wikipedia.org/wiki/Valencia_Street_Circuit'
    ),
    (
        13,
        N'spa',
        N'Circuit de Spa-Francorchamps',
        N'Spa',
        N'Belgium',
        50.4372,
        5.97139,
        401,
        N'http://en.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps'
    ),
    (
        14,
        N'monza',
        N'Autodromo Nazionale di Monza',
        N'Monza',
        N'Italy',
        45.6156,
        9.28111,
        162,
        N'http://en.wikipedia.org/wiki/Autodromo_Nazionale_Monza'
    ),
    (
        15,
        N'marina_bay',
        N'Marina Bay Street Circuit',
        N'Marina Bay',
        N'Singapore',
        1.2914,
        103.864,
        18,
        N'http://en.wikipedia.org/wiki/Marina_Bay_Street_Circuit'
    ),
    (
        16,
        N'fuji',
        N'Fuji Speedway',
        N'Oyama',
        N'Japan',
        35.3717,
        138.927,
        583,
        N'http://en.wikipedia.org/wiki/Fuji_Speedway'
    ),
    (
        17,
        N'shanghai',
        N'Shanghai International Circuit',
        N'Shanghai',
        N'China',
        31.3389,
        121.22,
        5,
        N'http://en.wikipedia.org/wiki/Shanghai_International_Circuit'
    ),
    (
        18,
        N'interlagos',
        N'Autódromo José Carlos Pace',
        N'São Paulo',
        N'Brazil',
        -23.7036,
        -46.6997,
        785,
        N'http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Jos%C3%A9_Carlos_Pace'
    ),
    (
        19,
        N'indianapolis',
        N'Indianapolis Motor Speedway',
        N'Indianapolis',
        N'USA',
        39.795,
        -86.2347,
        223,
        N'http://en.wikipedia.org/wiki/Indianapolis_Motor_Speedway'
    ),
    (
        20,
        N'nurburgring',
        N'Nürburgring',
        N'Nürburg',
        N'Germany',
        50.3356,
        6.9475,
        578,
        N'http://en.wikipedia.org/wiki/N%C3%BCrburgring'
    ),
    (
        21,
        N'imola',
        N'Autodromo Enzo e Dino Ferrari',
        N'Imola',
        N'Italy',
        44.3439,
        11.7167,
        37,
        N'http://en.wikipedia.org/wiki/Autodromo_Enzo_e_Dino_Ferrari'
    ),
    (
        22,
        N'suzuka',
        N'Suzuka Circuit',
        N'Suzuka',
        N'Japan',
        34.8431,
        136.541,
        45,
        N'http://en.wikipedia.org/wiki/Suzuka_Circuit'
    ),
    (
        24,
        N'yas_marina',
        N'Yas Marina Circuit',
        N'Abu Dhabi',
        N'UAE',
        24.4672,
        54.6031,
        3,
        N'http://en.wikipedia.org/wiki/Yas_Marina_Circuit'
    ),
    (
        25,
        N'galvez',
        N'Autódromo Juan y Oscar Gálvez',
        N'Buenos Aires',
        N'Argentina',
        -34.6943,
        -58.4593,
        8,
        N'http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Oscar_Alfredo_G%C3%A1lvez'
    ),
    (
        26,
        N'jerez',
        N'Circuito de Jerez',
        N'Jerez de la Frontera',
        N'Spain',
        36.7083,
        -6.03417,
        37,
        N'http://en.wikipedia.org/wiki/Circuito_Permanente_de_Jerez'
    ),
    (
        27,
        N'estoril',
        N'Autódromo do Estoril',
        N'Estoril',
        N'Portugal',
        38.7506,
        -9.39417,
        130,
        N'http://en.wikipedia.org/wiki/Aut%C3%B3dromo_do_Estoril'
    ),
    (
        28,
        N'okayama',
        N'Okayama International Circuit',
        N'Okayama',
        N'Japan',
        34.915,
        134.221,
        266,
        N'http://en.wikipedia.org/wiki/TI_Circuit'
    ),
    (
        29,
        N'adelaide',
        N'Adelaide Street Circuit',
        N'Adelaide',
        N'Australia',
        -34.9272,
        138.617,
        58,
        N'http://en.wikipedia.org/wiki/Adelaide_Street_Circuit'
    ),
    (
        30,
        N'kyalami',
        N'Kyalami',
        N'Midrand',
        N'South Africa',
        -25.9894,
        28.0767,
        1460,
        N'http://en.wikipedia.org/wiki/Kyalami'
    ),
    (
        31,
        N'donington',
        N'Donington Park',
        N'Castle Donington',
        N'UK',
        52.8306,
        -1.37528,
        88,
        N'http://en.wikipedia.org/wiki/Donington_Park'
    ),
    (
        32,
        N'rodriguez',
        N'Autódromo Hermanos Rodríguez',
        N'Mexico City',
        N'Mexico',
        19.4042,
        -99.0907,
        2227,
        N'http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Hermanos_Rodr%C3%ADguez'
    ),
    (
        33,
        N'phoenix',
        N'Phoenix street circuit',
        N'Phoenix',
        N'USA',
        33.4479,
        -112.075,
        345,
        N'http://en.wikipedia.org/wiki/Phoenix_street_circuit'
    ),
    (
        34,
        N'ricard',
        N'Circuit Paul Ricard',
        N'Le Castellet',
        N'France',
        43.2506,
        5.79167,
        432,
        N'http://en.wikipedia.org/wiki/Paul_Ricard_Circuit'
    ),
    (
        35,
        N'yeongam',
        N'Korean International Circuit',
        N'Yeongam County',
        N'Korea',
        34.7333,
        126.417,
        0,
        N'http://en.wikipedia.org/wiki/Korean_International_Circuit'
    ),
    (
        36,
        N'jacarepagua',
        N'Autódromo Internacional Nelson Piquet',
        N'Rio de Janeiro',
        N'Brazil',
        -22.9756,
        -43.395,
        1126,
        N'http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Internacional_Nelson_Piquet'
    ),
    (
        37,
        N'detroit',
        N'Detroit Street Circuit',
        N'Detroit',
        N'USA',
        42.3298,
        -83.0401,
        177,
        N'http://en.wikipedia.org/wiki/Detroit_street_circuit'
    ),
    (
        38,
        N'brands_hatch',
        N'Brands Hatch',
        N'Kent',
        N'UK',
        51.3569,
        0.263056,
        145,
        N'http://en.wikipedia.org/wiki/Brands_Hatch'
    ),
    (
        39,
        N'zandvoort',
        N'Circuit Park Zandvoort',
        N'Zandvoort',
        N'Netherlands',
        52.3888,
        4.54092,
        6,
        N'http://en.wikipedia.org/wiki/Circuit_Zandvoort'
    ),
    (
        40,
        N'zolder',
        N'Zolder',
        N'Heusden-Zolder',
        N'Belgium',
        50.9894,
        5.25694,
        36,
        N'http://en.wikipedia.org/wiki/Zolder'
    ),
    (
        41,
        N'dijon',
        N'Dijon-Prenois',
        N'Dijon',
        N'France',
        47.3625,
        4.89913,
        484,
        N'http://en.wikipedia.org/wiki/Dijon-Prenois'
    ),
    (
        42,
        N'dallas',
        N'Fair Park',
        N'Dallas',
        N'USA',
        32.7774,
        -96.7587,
        139,
        N'http://en.wikipedia.org/wiki/Fair_Park'
    ),
    (
        43,
        N'long_beach',
        N'Long Beach',
        N'California',
        N'USA',
        33.7651,
        -118.189,
        12,
        N'http://en.wikipedia.org/wiki/Long_Beach,_California'
    ),
    (
        44,
        N'las_vegas',
        N'Las Vegas Street Circuit',
        N'Nevada',
        N'USA',
        36.1162,
        -115.174,
        639,
        N'http://en.wikipedia.org/wiki/Las_Vegas_Street_Circuit'
    ),
    (
        45,
        N'jarama',
        N'Jarama',
        N'Madrid',
        N'Spain',
        40.6171,
        -3.58558,
        609,
        N'http://en.wikipedia.org/wiki/Circuito_Permanente_Del_Jarama'
    ),
    (
        46,
        N'watkins_glen',
        N'Watkins Glen',
        N'New York State',
        N'USA',
        42.3369,
        -76.9272,
        485,
        N'http://en.wikipedia.org/wiki/Watkins_Glen_International'
    ),
    (
        47,
        N'anderstorp',
        N'Scandinavian Raceway',
        N'Anderstorp',
        N'Sweden',
        57.2653,
        13.6042,
        153,
        N'http://en.wikipedia.org/wiki/Scandinavian_Raceway'
    ),
    (
        48,
        N'mosport',
        N'Mosport International Raceway',
        N'Ontario',
        N'Canada',
        44.0481,
        -78.6756,
        332,
        N'http://en.wikipedia.org/wiki/Mosport'
    ),
    (
        49,
        N'montjuic',
        N'Montjuïc',
        N'Barcelona',
        N'Spain',
        41.3664,
        2.15167,
        79,
        N'http://en.wikipedia.org/wiki/Montju%C3%AFc_circuit'
    ),
    (
        50,
        N'nivelles',
        N'Nivelles-Baulers',
        N'Brussels',
        N'Belgium',
        50.6211,
        4.32694,
        139,
        N'http://en.wikipedia.org/wiki/Nivelles-Baulers'
    ),
    (
        51,
        N'charade',
        N'Charade Circuit',
        N'Clermont-Ferrand',
        N'France',
        45.7472,
        3.03889,
        790,
        N'http://en.wikipedia.org/wiki/Charade_Circuit'
    ),
    (
        52,
        N'tremblant',
        N'Circuit Mont-Tremblant',
        N'Quebec',
        N'Canada',
        46.1877,
        -74.6099,
        214,
        N'http://en.wikipedia.org/wiki/Circuit_Mont-Tremblant'
    ),
    (
        53,
        N'essarts',
        N'Rouen-Les-Essarts',
        N'Rouen',
        N'France',
        49.3306,
        1.00458,
        81,
        N'http://en.wikipedia.org/wiki/Rouen-Les-Essarts'
    ),
    (
        54,
        N'lemans',
        N'Le Mans',
        N'Le Mans',
        N'France',
        47.95,
        0.224231,
        67,
        N'http://en.wikipedia.org/wiki/Circuit_de_la_Sarthe#Bugatti_Circuit'
    ),
    (
        55,
        N'reims',
        N'Reims-Gueux',
        N'Reims',
        N'France',
        49.2542,
        3.93083,
        88,
        N'http://en.wikipedia.org/wiki/Reims-Gueux'
    ),
    (
        56,
        N'george',
        N'Prince George Circuit',
        N'Eastern Cape Province',
        N'South Africa',
        -33.0486,
        27.8736,
        15,
        N'http://en.wikipedia.org/wiki/Prince_George_Circuit'
    ),
    (
        57,
        N'zeltweg',
        N'Zeltweg',
        N'Styria',
        N'Austria',
        47.2039,
        14.7478,
        676,
        N'http://en.wikipedia.org/wiki/Zeltweg_Airfield'
    ),
    (
        58,
        N'aintree',
        N'Aintree',
        N'Liverpool',
        N'UK',
        53.4769,
        -2.94056,
        20,
        N'http://en.wikipedia.org/wiki/Aintree_Motor_Racing_Circuit'
    ),
    (
        59,
        N'boavista',
        N'Circuito da Boavista',
        N'Oporto',
        N'Portugal',
        41.1705,
        -8.67325,
        28,
        N'http://en.wikipedia.org/wiki/Circuito_da_Boavista'
    ),
    (
        60,
        N'riverside',
        N'Riverside International Raceway',
        N'California',
        N'USA',
        33.937,
        -117.273,
        470,
        N'http://en.wikipedia.org/wiki/Riverside_International_Raceway'
    ),
    (
        61,
        N'avus',
        N'AVUS',
        N'Berlin',
        N'Germany',
        52.4806,
        13.2514,
        53,
        N'http://en.wikipedia.org/wiki/AVUS'
    ),
    (
        62,
        N'monsanto',
        N'Monsanto Park Circuit',
        N'Lisbon',
        N'Portugal',
        38.7197,
        -9.20306,
        158,
        N'http://en.wikipedia.org/wiki/Monsanto_Park_Circuit'
    ),
    (
        63,
        N'sebring',
        N'Sebring International Raceway',
        N'Florida',
        N'USA',
        27.4547,
        -81.3483,
        18,
        N'http://en.wikipedia.org/wiki/Sebring_Raceway'
    ),
    (
        64,
        N'ain-diab',
        N'Ain Diab',
        N'Casablanca',
        N'Morocco',
        33.5786,
        -7.6875,
        19,
        N'http://en.wikipedia.org/wiki/Ain-Diab_Circuit'
    ),
    (
        65,
        N'pescara',
        N'Pescara Circuit',
        N'Pescara',
        N'Italy',
        42.475,
        14.1508,
        129,
        N'http://en.wikipedia.org/wiki/Pescara_Circuit'
    ),
    (
        66,
        N'bremgarten',
        N'Circuit Bremgarten',
        N'Bern',
        N'Switzerland',
        46.9589,
        7.40194,
        551,
        N'http://en.wikipedia.org/wiki/Circuit_Bremgarten'
    ),
    (
        67,
        N'pedralbes',
        N'Circuit de Pedralbes',
        N'Barcelona',
        N'Spain',
        41.3903,
        2.11667,
        85,
        N'http://en.wikipedia.org/wiki/Pedralbes_Circuit'
    ),
    (
        68,
        N'buddh',
        N'Buddh International Circuit',
        N'Uttar Pradesh',
        N'India',
        28.3487,
        77.5331,
        194,
        N'http://en.wikipedia.org/wiki/Buddh_International_Circuit'
    ),
    (
        69,
        N'americas',
        N'Circuit of the Americas',
        N'Austin',
        N'USA',
        30.1328,
        -97.6411,
        161,
        N'http://en.wikipedia.org/wiki/Circuit_of_the_Americas'
    ),
    (
        70,
        N'red_bull_ring',
        N'Red Bull Ring',
        N'Spielberg',
        N'Austria',
        47.2197,
        14.7647,
        678,
        N'http://en.wikipedia.org/wiki/Red_Bull_Ring'
    ),
    (
        71,
        N'sochi',
        N'Sochi Autodrom',
        N'Sochi',
        N'Russia',
        43.4057,
        39.9578,
        2,
        N'http://en.wikipedia.org/wiki/Sochi_Autodrom'
    ),
    (
        73,
        N'baku',
        N'Baku City Circuit',
        N'Baku',
        N'Azerbaijan',
        40.3725,
        49.8533,
        -7,
        N'http://en.wikipedia.org/wiki/Baku_City_Circuit'
    ),
    (
        75,
        N'portimao',
        N'Autódromo Internacional do Algarve',
        N'Portimão',
        N'Portugal',
        37.227,
        -8.6267,
        108,
        N'http://en.wikipedia.org/wiki/Algarve_International_Circuit'
    ),
    (
        76,
        N'mugello',
        N'Autodromo Internazionale del Mugello',
        N'Mugello',
        N'Italy',
        43.9975,
        11.3719,
        255,
        N'http://en.wikipedia.org/wiki/Mugello_Circuit'
    ),
    (
        77,
        N'jeddah',
        N'Jeddah Corniche Circuit',
        N'Jeddah',
        N'Saudi Arabia',
        21.6319,
        39.1044,
        15,
        N'http://en.wikipedia.org/wiki/Jeddah_Street_Circuit'
    ),
    (
        78,
        N'losail',
        N'Losail International Circuit',
        N'Al Daayen',
        N'Qatar',
        25.49,
        51.4542,
        12,
        N'http://en.wikipedia.org/wiki/Losail_International_Circuit'
    ),
    (
        79,
        N'miami',
        N'Miami International Autodrome',
        N'Miami',
        N'USA',
        25.9581,
        -80.2389,
        0,
        N'http://en.wikipedia.org/wiki/Miami_International_Autodrome'
    ),
    (
        80,
        N'vegas',
        N'Las Vegas Strip Street Circuit',
        N'Las Vegas',
        N'United States',
        36.1147,
        -115.173,
        642,
        N'https://en.wikipedia.org/wiki/Las_Vegas_Grand_Prix#Circuit'
    );