INSERT INTO
    dbo.constructors (
        [constructorId],
        [constructorRef],
        [name],
        [nationality],
        [url]
    )
VALUES
    (
        1,
        N'mclaren',
        N'McLaren',
        N'British',
        N'http://en.wikipedia.org/wiki/McLaren'
    ),
    (
        2,
        N'bmw_sauber',
        N'BMW Sauber',
        N'German',
        N'http://en.wikipedia.org/wiki/BMW_Sauber'
    ),
    (
        3,
        N'williams',
        N'Williams',
        N'British',
        N'http://en.wikipedia.org/wiki/Williams_Grand_Prix_Engineering'
    ),
    (
        4,
        N'renault',
        N'Renault',
        N'French',
        N'http://en.wikipedia.org/wiki/Renault_in_Formula_One'
    ),
    (
        5,
        N'toro_rosso',
        N'Toro Rosso',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso'
    ),
    (
        6,
        N'ferrari',
        N'Ferrari',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Scuderia_Ferrari'
    ),
    (
        7,
        N'toyota',
        N'Toyota',
        N'Japanese',
        N'http://en.wikipedia.org/wiki/Toyota_Racing'
    ),
    (
        8,
        N'super_aguri',
        N'Super Aguri',
        N'Japanese',
        N'http://en.wikipedia.org/wiki/Super_Aguri_F1'
    ),
    (
        9,
        N'red_bull',
        N'Red Bull',
        N'Austrian',
        N'http://en.wikipedia.org/wiki/Red_Bull_Racing'
    ),
    (
        10,
        N'force_india',
        N'Force India',
        N'Indian',
        N'http://en.wikipedia.org/wiki/Racing_Point_Force_India'
    ),
    (
        11,
        N'honda',
        N'Honda',
        N'Japanese',
        N'http://en.wikipedia.org/wiki/Honda_Racing_F1'
    ),
    (
        12,
        N'spyker',
        N'Spyker',
        N'Dutch',
        N'http://en.wikipedia.org/wiki/Spyker_F1'
    ),
    (
        13,
        N'mf1',
        N'MF1',
        N'Russian',
        N'http://en.wikipedia.org/wiki/Midland_F1_Racing'
    ),
    (
        14,
        N'spyker_mf1',
        N'Spyker MF1',
        N'Dutch',
        N'http://en.wikipedia.org/wiki/Midland_F1_Racing'
    ),
    (
        15,
        N'sauber',
        N'Sauber',
        N'Swiss',
        N'http://en.wikipedia.org/wiki/Sauber_Motorsport'
    ),
    (
        16,
        N'bar',
        N'BAR',
        N'British',
        N'http://en.wikipedia.org/wiki/British_American_Racing'
    ),
    (
        17,
        N'jordan',
        N'Jordan',
        N'Irish',
        N'http://en.wikipedia.org/wiki/Jordan_Grand_Prix'
    ),
    (
        18,
        N'minardi',
        N'Minardi',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Minardi'
    ),
    (
        19,
        N'jaguar',
        N'Jaguar',
        N'British',
        N'http://en.wikipedia.org/wiki/Jaguar_Racing'
    ),
    (
        20,
        N'prost',
        N'Prost',
        N'French',
        N'http://en.wikipedia.org/wiki/Prost_Grand_Prix'
    ),
    (
        21,
        N'arrows',
        N'Arrows',
        N'British',
        N'http://en.wikipedia.org/wiki/Arrows_Grand_Prix_International'
    ),
    (
        22,
        N'benetton',
        N'Benetton',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Benetton_Formula'
    ),
    (
        23,
        N'brawn',
        N'Brawn',
        N'British',
        N'http://en.wikipedia.org/wiki/Brawn_GP'
    ),
    (
        24,
        N'stewart',
        N'Stewart',
        N'British',
        N'http://en.wikipedia.org/wiki/Stewart_Grand_Prix'
    ),
    (
        25,
        N'tyrrell',
        N'Tyrrell',
        N'British',
        N'http://en.wikipedia.org/wiki/Tyrrell_Racing'
    ),
    (
        26,
        N'lola',
        N'Lola',
        N'British',
        N'http://en.wikipedia.org/wiki/MasterCard_Lola'
    ),
    (
        27,
        N'ligier',
        N'Ligier',
        N'French',
        N'http://en.wikipedia.org/wiki/Ligier'
    ),
    (
        28,
        N'forti',
        N'Forti',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Forti'
    ),
    (
        29,
        N'footwork',
        N'Footwork',
        N'British',
        N'http://en.wikipedia.org/wiki/Footwork_Arrows'
    ),
    (
        30,
        N'pacific',
        N'Pacific',
        N'British',
        N'http://en.wikipedia.org/wiki/Pacific_Racing'
    ),
    (
        31,
        N'simtek',
        N'Simtek',
        N'British',
        N'http://en.wikipedia.org/wiki/Simtek'
    ),
    (
        32,
        N'team_lotus',
        N'Team Lotus',
        N'British',
        N'http://en.wikipedia.org/wiki/Team_Lotus'
    ),
    (
        33,
        N'larrousse',
        N'Larrousse',
        N'French',
        N'http://en.wikipedia.org/wiki/Larrousse'
    ),
    (
        34,
        N'brabham',
        N'Brabham',
        N'British',
        N'http://en.wikipedia.org/wiki/Brabham'
    ),
    (
        35,
        N'dallara',
        N'Dallara',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Dallara'
    ),
    (
        36,
        N'fondmetal',
        N'Fondmetal',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Fondmetal'
    ),
    (
        37,
        N'march',
        N'March',
        N'British',
        N'http://en.wikipedia.org/wiki/March_Engineering'
    ),
    (
        38,
        N'moda',
        N'Andrea Moda',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Andrea_Moda_Formula'
    ),
    (
        39,
        N'ags',
        N'AGS',
        N'French',
        N'http://en.wikipedia.org/wiki/Automobiles_Gonfaronnaises_Sportives'
    ),
    (
        40,
        N'lambo',
        N'Lambo',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Modena_(racing_team)'
    ),
    (
        41,
        N'leyton',
        N'Leyton House',
        N'British',
        N'http://en.wikipedia.org/wiki/Leyton_House'
    ),
    (
        42,
        N'coloni',
        N'Coloni',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Enzo_Coloni_Racing_Car_Systems'
    ),
    (
        44,
        N'eurobrun',
        N'Euro Brun',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Euro_Brun'
    ),
    (
        45,
        N'osella',
        N'Osella',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Osella'
    ),
    (
        46,
        N'onyx',
        N'Onyx',
        N'British',
        N'http://en.wikipedia.org/wiki/Onyx_(racing_team)'
    ),
    (
        47,
        N'life',
        N'Life',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Life_(Racing_Team)'
    ),
    (
        48,
        N'rial',
        N'Rial',
        N'German',
        N'http://en.wikipedia.org/wiki/Rial_%28racing_team%29'
    ),
    (
        49,
        N'zakspeed',
        N'Zakspeed',
        N'German',
        N'http://en.wikipedia.org/wiki/Zakspeed'
    ),
    (
        50,
        N'ram',
        N'RAM',
        N'British',
        N'http://en.wikipedia.org/wiki/RAM_Racing'
    ),
    (
        51,
        N'alfa',
        N'Alfa Romeo',
        N'Swiss',
        N'http://en.wikipedia.org/wiki/Alfa_Romeo_in_Formula_One'
    ),
    (
        52,
        N'spirit',
        N'Spirit',
        N'British',
        N'http://en.wikipedia.org/wiki/Spirit_(racing_team)'
    ),
    (
        53,
        N'toleman',
        N'Toleman',
        N'British',
        N'http://en.wikipedia.org/wiki/Toleman'
    ),
    (
        54,
        N'ats',
        N'ATS',
        N'Italian',
        N'http://en.wikipedia.org/wiki/ATS_(wheels)'
    ),
    (
        55,
        N'theodore',
        N'Theodore',
        N'Hong Kong',
        N'http://en.wikipedia.org/wiki/Theodore_Racing'
    ),
    (
        56,
        N'fittipaldi',
        N'Fittipaldi',
        N'Brazilian',
        N'http://en.wikipedia.org/wiki/Fittipaldi_%28constructor%29'
    ),
    (
        57,
        N'ensign',
        N'Ensign',
        N'British',
        N'http://en.wikipedia.org/wiki/Ensign_%28racing_team%29'
    ),
    (
        58,
        N'shadow',
        N'Shadow',
        N'British',
        N'http://en.wikipedia.org/wiki/Shadow_Racing_Cars'
    ),
    (
        59,
        N'wolf',
        N'Wolf',
        N'Canadian',
        N'http://en.wikipedia.org/wiki/Walter_Wolf_Racing'
    ),
    (
        60,
        N'merzario',
        N'Merzario',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Merzario'
    ),
    (
        61,
        N'kauhsen',
        N'Kauhsen',
        N'German',
        N'http://en.wikipedia.org/wiki/Kauhsen'
    ),
    (
        62,
        N'rebaque',
        N'Rebaque',
        N'Mexican',
        N'http://en.wikipedia.org/wiki/Rebaque'
    ),
    (
        63,
        N'surtees',
        N'Surtees',
        N'British',
        N'http://en.wikipedia.org/wiki/Surtees'
    ),
    (
        64,
        N'hesketh',
        N'Hesketh',
        N'British',
        N'http://en.wikipedia.org/wiki/Hesketh_Racing'
    ),
    (
        65,
        N'martini',
        N'Martini',
        N'French',
        N'http://en.wikipedia.org/wiki/Martini_(cars)'
    ),
    (
        66,
        N'brm',
        N'BRM',
        N'British',
        N'http://en.wikipedia.org/wiki/BRM'
    ),
    (
        67,
        N'penske',
        N'Penske',
        N'American',
        N'http://en.wikipedia.org/wiki/Penske_Racing'
    ),
    (
        68,
        N'lec',
        N'LEC',
        N'British',
        N'http://en.wikipedia.org/wiki/LEC_(Formula_One)'
    ),
    (
        69,
        N'mcguire',
        N'McGuire',
        N'Australian',
        N'http://en.wikipedia.org/wiki/McGuire_(Formula_One)'
    ),
    (
        70,
        N'boro',
        N'Boro',
        N'Dutch',
        N'http://en.wikipedia.org/wiki/Boro_(Formula_One)'
    ),
    (
        71,
        N'apollon',
        N'Apollon',
        N'Swiss',
        N'http://en.wikipedia.org/wiki/Apollon_(Formula_One)'
    ),
    (
        72,
        N'kojima',
        N'Kojima',
        N'Japanese',
        N'http://en.wikipedia.org/wiki/Kojima_Engineering'
    ),
    (
        73,
        N'parnelli',
        N'Parnelli',
        N'American',
        N'http://en.wikipedia.org/wiki/Parnelli'
    ),
    (
        74,
        N'maki',
        N'Maki',
        N'Japanese',
        N'http://en.wikipedia.org/wiki/Maki_(cars)'
    ),
    (
        75,
        N'hill',
        N'Embassy Hill',
        N'British',
        N'http://en.wikipedia.org/wiki/Hill_(constructor)'
    ),
    (
        76,
        N'lyncar',
        N'Lyncar',
        N'British',
        N'http://en.wikipedia.org/wiki/Lyncar'
    ),
    (
        77,
        N'trojan',
        N'Trojan',
        N'British',
        N'http://en.wikipedia.org/wiki/Trojan_(Racing_team)'
    ),
    (
        78,
        N'amon',
        N'Amon',
        N 'New Zealander',
        N'http://en.wikipedia.org/wiki/Amon_(Formula_One_team)'
    ),
    (
        79,
        N'token',
        N'Token',
        N'British',
        N'http://en.wikipedia.org/wiki/Token_(Racing_team)'
    ),
    (
        80,
        N'iso_marlboro',
        N'Iso Marlboro',
        N'British',
        N'http://en.wikipedia.org/wiki/Iso_Marlboro'
    ),
    (
        81,
        N'tecno',
        N'Tecno',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Tecno'
    ),
    (
        82,
        N'matra',
        N'Matra',
        N'French',
        N'http://en.wikipedia.org/wiki/Matra'
    ),
    (
        83,
        N'politoys',
        N'Politoys',
        N'British',
        N'http://en.wikipedia.org/wiki/Frank_Williams_Racing_Cars'
    ),
    (
        84,
        N'connew',
        N'Connew',
        N'British',
        N'http://en.wikipedia.org/wiki/Connew'
    ),
    (
        85,
        N'bellasi',
        N'Bellasi',
        N'Swiss',
        N'http://en.wikipedia.org/wiki/Bellasi'
    ),
    (
        86,
        N'tomaso',
        N'De Tomaso',
        N'Italian',
        N'http://en.wikipedia.org/wiki/De_Tomaso'
    ),
    (
        87,
        N'cooper',
        N'Cooper',
        N'British',
        N'http://en.wikipedia.org/wiki/Cooper_Car_Company'
    ),
    (
        88,
        N'eagle',
        N'Eagle',
        N'American',
        N'http://en.wikipedia.org/wiki/Anglo_American_Racers'
    ),
    (
        89,
        N'lds',
        N'LDS',
        N'South African',
        N'http://en.wikipedia.org/wiki/LDS_(automobile)'
    ),
    (
        90,
        N'protos',
        N'Protos',
        N'British',
        N'http://en.wikipedia.org/wiki/Protos_(constructor)'
    ),
    (
        91,
        N'shannon',
        N'Shannon',
        N'British',
        N'http://en.wikipedia.org/wiki/Shannon_(Formula_One)'
    ),
    (
        92,
        N'scirocco',
        N'Scirocco',
        N'British',
        N'http://en.wikipedia.org/wiki/Scirocco-Powell'
    ),
    (
        93,
        N're',
        N'RE',
        N'Rhodesian',
        N'http://en.wikipedia.org/wiki/RE_%28automobile%29'
    ),
    (
        94,
        N'brp',
        N'BRP',
        N'British',
        N'http://en.wikipedia.org/wiki/British_Racing_Partnership'
    ),
    (
        95,
        N'porsche',
        N'Porsche',
        N'German',
        N'http://en.wikipedia.org/wiki/Porsche_in_Formula_One'
    ),
    (
        96,
        N'derrington',
        N'Derrington',
        N'British',
        N'http://en.wikipedia.org/wiki/Derrington-Francis'
    ),
    (
        97,
        N'gilby',
        N'Gilby',
        N'British',
        N'http://en.wikipedia.org/wiki/Gilby'
    ),
    (
        98,
        N'stebro',
        N'Stebro',
        N'Canadian',
        N'http://en.wikipedia.org/wiki/Stebro'
    ),
    (
        99,
        N'emeryson',
        N'Emeryson',
        N'British',
        N'http://en.wikipedia.org/wiki/Emeryson'
    ),
    (
        100,
        N'enb',
        N 'ENB',
        N'Belgian',
        N 'http://en.wikipedia.org/wiki/Ecurie_Nationale_Belge'
    ),
    (
        101,
        N'jbw',
        N'JBW',
        N'British',
        N'http://en.wikipedia.org/wiki/JBW'
    ),
    (
        102,
        N'ferguson',
        N'Ferguson',
        N'British',
        N'http://en.wikipedia.org/wiki/Ferguson_Research_Ltd.'
    ),
    (
        103,
        N'mbm',
        N'MBM',
        N'Swiss',
        N'http://en.wikipedia.org/wiki/Monteverdi_Basel_Motors'
    ),
    (
        104,
        N'behra-porsche',
        N'Behra-Porsche',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Behra-Porsche'
    ),
    (
        105,
        N'maserati',
        N'Maserati',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Maserati'
    ),
    (
        106,
        N'scarab',
        N'Scarab',
        N'American',
        N'http://en.wikipedia.org/wiki/Scarab_(constructor)'
    ),
    (
        107,
        N'watson',
        N'Watson',
        N'American',
        N'http://en.wikipedia.org/wiki/A.J._Watson'
    ),
    (
        108,
        N'epperly',
        N'Epperly',
        N'American',
        N'http://en.wikipedia.org/wiki/Epperly'
    ),
    (
        109,
        N'phillips',
        N'Phillips',
        N'American',
        N'http://en.wikipedia.org/wiki/Phillips_(constructor)'
    ),
    (
        110,
        N'lesovsky',
        N'Lesovsky',
        N'American',
        N'http://en.wikipedia.org/wiki/Lesovsky'
    ),
    (
        111,
        N'trevis',
        N'Trevis',
        N'American',
        N'http://en.wikipedia.org/wiki/Trevis'
    ),
    (
        112,
        N'meskowski',
        N'Meskowski',
        N'American',
        N'http://en.wikipedia.org/wiki/Meskowski'
    ),
    (
        113,
        N'kurtis_kraft',
        N'Kurtis Kraft',
        N'American',
        N'http://en.wikipedia.org/wiki/Kurtis_Kraft'
    ),
    (
        114,
        N'kuzma',
        N'Kuzma',
        N'American',
        N'http://en.wikipedia.org/wiki/Kuzma_(constructor)'
    ),
    (
        115,
        N'vhristensen',
        N'Christensen',
        N'American',
        N'http://en.wikipedia.org/wiki/Christensen_(constructor)'
    ),
    (
        116,
        N'ewing',
        N'Ewing',
        N'American',
        N'http://en.wikipedia.org/wiki/Ewing_(constructor)'
    ),
    (
        117,
        N'aston_martin',
        N'Aston Martin',
        N'British',
        N'http://en.wikipedia.org/wiki/Aston_Martin_in_Formula_One'
    ),
    (
        118,
        N'vanwall',
        N'Vanwall',
        N'British',
        N'http://en.wikipedia.org/wiki/Vanwall'
    ),
    (
        119,
        N'moore',
        N'Moore',
        N'American',
        N'http://en.wikipedia.org/wiki/Moore_(constructor)'
    ),
    (
        120,
        N'dunn',
        N'Dunn',
        N'American',
        N'http://en.wikipedia.org/wiki/Dunn_Engineering'
    ),
    (
        121,
        N'elder',
        N'Elder',
        N'American',
        N'http://en.wikipedia.org/wiki/Elder_(constructor)'
    ),
    (
        122,
        N'sutton',
        N'Sutton',
        N'American',
        N'http://en.wikipedia.org/wiki/Sutton_(constructor)'
    ),
    (
        123,
        N'fry',
        N'Fry',
        N'British',
        N'http://en.wikipedia.org/wiki/Fry_(racing_team)'
    ),
    (
        124,
        N'tec-mec',
        N'Tec-Mec',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Tec-Mec'
    ),
    (
        125,
        N'connaught',
        N'Connaught',
        N'British',
        N'http://en.wikipedia.org/wiki/Connaught_Engineering'
    ),
    (
        126,
        N'alta',
        N'Alta',
        N'British',
        N'http://en.wikipedia.org/wiki/Alta_auto_racing_team'
    ),
    (
        127,
        N'osca',
        N'OSCA',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Officine_Specializate_Costruzione_Automobili'
    ),
    (
        128,
        N'gordini',
        N'Gordini',
        N'French',
        N'http://en.wikipedia.org/wiki/Gordini'
    ),
    (
        129,
        N'stevens',
        N'Stevens',
        N'American',
        N'http://en.wikipedia.org/wiki/Stevens_(constructor)'
    ),
    (
        130,
        N'bugatti',
        N'Bugatti',
        N'French',
        N'http://en.wikipedia.org/wiki/Bugatti'
    ),
    (
        131,
        N'mercedes',
        N'Mercedes',
        N'German',
        N'http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One'
    ),
    (
        132,
        N'lancia',
        N'Lancia',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Lancia_in_Formula_One'
    ),
    (
        133,
        N'hwm',
        N'HWM',
        N'British',
        N'http://en.wikipedia.org/wiki/Hersham_and_Walton_Motors'
    ),
    (
        134,
        N'schroeder',
        N'Schroeder',
        N'American',
        N'http://en.wikipedia.org/wiki/Schroeder_(constructor)'
    ),
    (
        135,
        N'pawl',
        N'Pawl',
        N'American',
        N'http://en.wikipedia.org/wiki/Pawl_(constructor)'
    ),
    (
        136,
        N'pankratz',
        N'Pankratz',
        N'American',
        N'http://en.wikipedia.org/wiki/Pankratz'
    ),
    (
        137,
        N'arzani-volpini',
        N'Arzani-Volpini',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Arzani-Volpini'
    ),
    (
        138,
        N'nichels',
        N 'Nichels',
        N'American',
        N 'http://en.wikipedia.org/wiki/Nichels'
    ),
    (
        139,
        N'bromme',
        N'Bromme',
        N'American',
        N'http://en.wikipedia.org/wiki/Bromme'
    ),
    (
        140,
        N'klenk',
        N'Klenk',
        N'German',
        N'http://en.wikipedia.org/wiki/Klenk'
    ),
    (
        141,
        N'simca',
        N'Simca',
        N'French',
        N'http://en.wikipedia.org/wiki/Simca'
    ),
    (
        142,
        N'turner',
        N'Turner',
        N'American',
        N'http://en.wikipedia.org/wiki/Turner_(constructor)'
    ),
    (
        143,
        N'del_roy',
        N'Del Roy',
        N'American',
        N'http://en.wikipedia.org/wiki/Del_Roy'
    ),
    (
        144,
        N'veritas',
        N'Veritas',
        N'German',
        N'http://en.wikipedia.org/wiki/Veritas_(constructor)'
    ),
    (
        145,
        N'bmw',
        N'BMW',
        N'German',
        N'http://en.wikipedia.org/wiki/BMW'
    ),
    (
        146,
        N'emw',
        N'EMW',
        N'East German',
        N'http://en.wikipedia.org/wiki/Eisenacher_Motorenwerk'
    ),
    (
        147,
        N'afm',
        N'AFM',
        N'German',
        N'http://en.wikipedia.org/wiki/Alex_von_Falkenhausen_Motorenbau'
    ),
    (
        148,
        N'frazer_nash',
        N 'Frazer Nash',
        N'British',
        N 'http://en.wikipedia.org/wiki/Frazer_Nash'
    ),
    (
        149,
        N'sherman',
        N'Sherman',
        N'American',
        N'http://en.wikipedia.org/wiki/Sherman_(constructor)'
    ),
    (
        150,
        N'deidt',
        N'Deidt',
        N'American',
        N'http://en.wikipedia.org/wiki/Deidt'
    ),
    (
        151,
        N'era',
        N'ERA',
        N'British',
        N'http://en.wikipedia.org/wiki/English_Racing_Automobiles'
    ),
    (
        152,
        N'butterworth',
        N'Aston Butterworth',
        N'British',
        N'http://en.wikipedia.org/wiki/Aston_Butterworth'
    ),
    (
        153,
        N'cisitalia',
        N'Cisitalia',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Cisitalia'
    ),
    (
        154,
        N'lago',
        N'Talbot-Lago',
        N'French',
        N'http://en.wikipedia.org/wiki/Talbot-Lago'
    ),
    (
        155,
        N'hall',
        N'Hall',
        N'American',
        N'http://en.wikipedia.org/wiki/Hall_(constructor)'
    ),
    (
        156,
        N'marchese',
        N'Marchese',
        N'American',
        N'http://en.wikipedia.org/wiki/Marchese_(constructor)'
    ),
    (
        157,
        N'langley',
        N'Langley',
        N'American',
        N'http://en.wikipedia.org/wiki/Langley_(constructor)'
    ),
    (
        158,
        N'rae',
        N'Rae',
        N'American',
        N'http://en.wikipedia.org/wiki/Rae_(motorsport)'
    ),
    (
        159,
        N'olson',
        N'Olson',
        N'American',
        N'http://en.wikipedia.org/wiki/Olson_(constructor)'
    ),
    (
        160,
        N'wetteroth',
        N'Wetteroth',
        N'American',
        N'http://en.wikipedia.org/wiki/Wetteroth'
    ),
    (
        161,
        N'adams',
        N'Adams',
        N'American',
        N'http://en.wikipedia.org/wiki/Adams_(constructor)'
    ),
    (
        162,
        N'snowberger',
        N'Snowberger',
        N'American',
        N'http://en.wikipedia.org/wiki/Snowberger'
    ),
    (
        163,
        N'milano',
        N'Milano',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Scuderia_Milano'
    ),
    (
        164,
        N'hrt',
        N'HRT',
        N'Spanish',
        N'http://en.wikipedia.org/wiki/Hispania_Racing'
    ),
    (
        166,
        N'virgin',
        N'Virgin',
        N'British',
        N'http://en.wikipedia.org/wiki/Virgin_Racing'
    ),
    (
        167,
        N'cooper-maserati',
        N'Cooper-Maserati',
        N'British',
        N'http://en.wikipedia.org/wiki/Cooper_Car_Company'
    ),
    (
        168,
        N'cooper-osca',
        N'Cooper-OSCA',
        N'British',
        N'http://en.wikipedia.org/wiki/Cooper_Car_Company'
    ),
    (
        169,
        N'cooper-borgward',
        N'Cooper-Borgward',
        N'British',
        N'http://en.wikipedia.org/wiki/Cooper_Car_Company'
    ),
    (
        170,
        N'cooper-climax',
        N'Cooper-Climax',
        N'British',
        N'http://en.wikipedia.org/wiki/Cooper_Car_Company'
    ),
    (
        171,
        N'cooper-castellotti',
        N'Cooper-Castellotti',
        N'British',
        N'http://en.wikipedia.org/wiki/Cooper_Car_Company'
    ),
    (
        172,
        N'lotus-climax',
        N'Lotus-Climax',
        N'British',
        N'http://en.wikipedia.org/wiki/Team_Lotus'
    ),
    (
        173,
        N'lotus-maserati',
        N'Lotus-Maserati',
        N'British',
        N'http://en.wikipedia.org/wiki/Team_Lotus'
    ),
    (
        174,
        N'de_tomaso-osca',
        N'De Tomaso-Osca',
        N'Italian',
        N'http://en.wikipedia.org/wiki/De_Tomaso'
    ),
    (
        175,
        N'de_tomaso-alfa_romeo',
        N'De Tomaso-Alfa Romeo',
        N'Italian',
        N'http://en.wikipedia.org/wiki/De_Tomaso'
    ),
    (
        176,
        N'lotus-brm',
        N'Lotus-BRM',
        N'British',
        N'http://en.wikipedia.org/wiki/Team_Lotus'
    ),
    (
        177,
        N'lotus-borgward',
        N'Lotus-Borgward',
        N'British',
        N'http://en.wikipedia.org/wiki/Team_Lotus'
    ),
    (
        178,
        N'cooper-alfa_romeo',
        N'Cooper-Alfa Romeo',
        N'British',
        N'http://en.wikipedia.org/wiki/Cooper_Car_Company'
    ),
    (
        179,
        N'de_tomaso-ferrari',
        N'De Tomaso-Ferrari',
        N'Italian',
        N'http://en.wikipedia.org/wiki/De_Tomaso'
    ),
    (
        180,
        N'lotus-ford',
        N'Lotus-Ford',
        N'British',
        N'http://en.wikipedia.org/wiki/Team_Lotus'
    ),
    (
        181,
        N'brabham-brm',
        N'Brabham-BRM',
        N'British',
        N'http://en.wikipedia.org/wiki/Brabham'
    ),
    (
        182,
        N'brabham-ford',
        N'Brabham-Ford',
        N'British',
        N'http://en.wikipedia.org/wiki/Brabham'
    ),
    (
        183,
        N'brabham-climax',
        N'Brabham-Climax',
        N'British',
        N'http://en.wikipedia.org/wiki/Brabham'
    ),
    (
        184,
        N'lds-climax',
        N'LDS-Climax',
        N'South African',
        N'http://en.wikipedia.org/wiki/LDS_(automobile)'
    ),
    (
        185,
        N'lds-alfa_romeo',
        N'LDS-Alfa Romeo',
        N'South African',
        N'http://en.wikipedia.org/wiki/LDS_(automobile)'
    ),
    (
        186,
        N'cooper-ford',
        N'Cooper-Ford',
        N'British',
        N'http://en.wikipedia.org/wiki/Cooper_Car_Company'
    ),
    (
        187,
        N'mclaren-ford',
        N'McLaren-Ford',
        N'British',
        N'http://en.wikipedia.org/wiki/Team_McLaren'
    ),
    (
        188,
        N'mclaren-seren',
        N'McLaren-Serenissima',
        N'British',
        N'http://en.wikipedia.org/wiki/Team_McLaren'
    ),
    (
        189,
        N'eagle-climax',
        N'Eagle-Climax',
        N'American',
        N'http://en.wikipedia.org/wiki/Anglo_American_Racers'
    ),
    (
        190,
        N'eagle-weslake',
        N'Eagle-Weslake',
        N'American',
        N'http://en.wikipedia.org/wiki/Anglo_American_Racers'
    ),
    (
        191,
        N'brabham-repco',
        N'Brabham-Repco',
        N'British',
        N'http://en.wikipedia.org/wiki/Brabham'
    ),
    (
        192,
        N'cooper-ferrari',
        N'Cooper-Ferrari',
        N'British',
        N'http://en.wikipedia.org/wiki/Cooper_Car_Company'
    ),
    (
        193,
        N'cooper-ats',
        N'Cooper-ATS',
        N'British',
        N'http://en.wikipedia.org/wiki/Cooper_Car_Company'
    ),
    (
        194,
        N'mclaren-brm',
        N'McLaren-BRM',
        N'British',
        N'http://en.wikipedia.org/wiki/McLaren_(racing)'
    ),
    (
        195,
        N'cooper-brm',
        N'Cooper-BRM',
        N'British',
        N'http://en.wikipedia.org/wiki/Cooper_Car_Company'
    ),
    (
        196,
        N'matra-ford',
        N'Matra-Ford',
        N'French',
        N'http://en.wikipedia.org/wiki/Matra'
    ),
    (
        197,
        N'brm-ford',
        N'BRM-Ford',
        N'British',
        N'http://en.wikipedia.org/wiki/BRM'
    ),
    (
        198,
        N'mclaren-alfa_romeo',
        N'McLaren-Alfa Romeo',
        N'British',
        N'http://en.wikipedia.org/wiki/McLaren_(racing)'
    ),
    (
        199,
        N'march-alfa_romeo',
        N'March-Alfa Romeo',
        N'British',
        N'http://en.wikipedia.org/wiki/March_Engineering'
    ),
    (
        200,
        N'march-ford',
        N'March-Ford',
        N'British',
        N'http://en.wikipedia.org/wiki/March_Engineering'
    ),
    (
        201,
        N'lotus-pw',
        N'Lotus-Pratt &amp; Whitney',
        N'British',
        N'http://en.wikipedia.org/wiki/Team_Lotus'
    ),
    (
        202,
        N'shadow-ford',
        N'Shadow-Ford',
        N'British',
        N'http://en.wikipedia.org/wiki/Shadow_Racing_Cars'
    ),
    (
        203,
        N'shadow-matra',
        N'Shadow-Matra',
        N'British',
        N'http://en.wikipedia.org/wiki/Shadow_Racing_Cars'
    ),
    (
        204,
        N'brabham-alfa_romeo',
        N'Brabham-Alfa Romeo',
        N'British',
        N'http://en.wikipedia.org/wiki/Brabham'
    ),
    (
        205,
        N'lotus_racing',
        N'Lotus',
        N'Malaysian',
        N'http://en.wikipedia.org/wiki/Lotus_Racing'
    ),
    (
        206,
        N'marussia',
        N'Marussia',
        N'Russian',
        N'http://en.wikipedia.org/wiki/Marussia_F1'
    ),
    (
        207,
        N'caterham',
        N'Caterham',
        N'Malaysian',
        N'http://en.wikipedia.org/wiki/Caterham_F1'
    ),
    (
        208,
        N'lotus_f1',
        N'Lotus F1',
        N'British',
        N'http://en.wikipedia.org/wiki/Lotus_F1'
    ),
    (
        209,
        N'manor',
        N'Manor Marussia',
        N'British',
        N'http://en.wikipedia.org/wiki/Manor_Motorsport'
    ),
    (
        210,
        N'haas',
        N'Haas F1 Team',
        N'American',
        N'http://en.wikipedia.org/wiki/Haas_F1_Team'
    ),
    (
        211,
        N'racing_point',
        N'Racing Point',
        N'British',
        N'http://en.wikipedia.org/wiki/Racing_Point_F1_Team'
    ),
    (
        213,
        N'alphatauri',
        N'AlphaTauri',
        N'Italian',
        N'http://en.wikipedia.org/wiki/Scuderia_AlphaTauri'
    ),
    (
        214,
        N'alpine',
        N'Alpine F1 Team',
        N'French',
        N'http://en.wikipedia.org/wiki/Alpine_F1_Team'
    ),
    (
        215,
        N'rb',
        N'RB F1 Team',
        N'Italian',
        N'http://en.wikipedia.org/wiki/RB_Formula_One_Team'
    );